name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Docker Scan
        shell: powershell
        run: |
          docker run --rm `
          -v "${{ github.workspace }}:/zap/wrk/:rw" `
          ghcr.io/zaproxy/zaproxy:stable `
          zap-baseline.py `
          -t http://host.docker.internal:8080/courier/ `
          -r zap-report.html || exit 0

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: zap-report.html
